import PagePlaceholder from '../../components/ui/PagePlaceholder'

import fondoVipla   from '../../assets/VIPLA/FONDO-VIPLA.png'

import vipla1   from '../../assets/VIPLA/fotos/VIPLA_1WEB.png'
import vipla2   from '../../assets/VIPLA/fotos/VIPLA_2WEB.png'
import vipla3   from '../../assets/VIPLA/fotos/VIPLA_3WEB.png'
import vipla4   from '../../assets/VIPLA/fotos/VIPLA_4WEB.png'
import vipla5   from '../../assets/VIPLA/fotos/VIPLA_5WEB.png'
import vipla6   from '../../assets/VIPLA/fotos/VIPLA_6WEB.png'
import vipla7   from '../../assets/VIPLA/fotos/VIPLA_7WEB.png'
import vipla8   from '../../assets/VIPLA/fotos/VIPLA_8WEB.png'
import vipla9   from '../../assets/VIPLA/fotos/VIPLA_9WEB.png'
import vipla10  from '../../assets/VIPLA/fotos/VIPLA_10WEB.png'
import vipla11  from '../../assets/VIPLA/fotos/VIPLA_11WEB.png'
import vipla12  from '../../assets/VIPLA/fotos/VIPLA_12WEB.png'
import vipla13  from '../../assets/VIPLA/fotos/VIPLA_13WEB.png'
import vipla14  from '../../assets/VIPLA/fotos/VIPLA_14WEB.png'
import vipla15  from '../../assets/VIPLA/fotos/VIPLA_15WEB.png'
import vipla16  from '../../assets/VIPLA/fotos/VIPLA_16WEB.png'
import vipla17  from '../../assets/VIPLA/fotos/VIPLA_17WEB.png'
import vipla18  from '../../assets/VIPLA/fotos/VIPLA_18WEB.png'
import vipla19  from '../../assets/VIPLA/fotos/VIPLA_19WEB.png'
import vipla20  from '../../assets/VIPLA/fotos/VIPLAWEB.png'

import viplaPlano from '../../assets/VIPLA/Plano_Vipla.jpg'

import viplaIso1 from '../../assets/VIPLA/Edificios Isométricos/VIPLA2_1.png'
import viplaIso2 from '../../assets/VIPLA/Edificios Isométricos/VIPLA2.png'
import viplaIso3 from '../../assets/VIPLA/Edificios Isométricos/VIPLA3.png'
import viplaIso4 from '../../assets/VIPLA/Edificios Isométricos/VIPLA2_Azul_1.png'
import viplaIso5 from '../../assets/VIPLA/Edificios Isométricos/VIPLA2_Azul.png'
import viplaIso6 from '../../assets/VIPLA/Edificios Isométricos/VIPLA3_Azul.png'

export default function VIPLA() {
  return (
    <PagePlaceholder
      numero="03"
      titulo="VIPLA"
      descripcion="Industria del Vidrio Plano. Texto, carrusel de fotos actuales, imagen de maqueta 3D y plano."
    />
  )
}
